// packages/remote/src/App.vue
<template>
  <Header/>
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: remote</div>
    <div>Framework: vue3</div>
    <div>Language: JavaScript</div>
    <div>CSS: Tailwind</div>
  </div>
</template>

<script>
  import Header from './Header.vue';
  export default {
    components: {
      Header
    }
  }
</script>

// packages/react-host/src/App.tsx
import React, { useRef, useEffect } from "react";
import ReactDOM from "react-dom";

import placeHeader from "remote/placeHeader";
import "./index.scss";

const App = () => {
  const headerRef = useRef(null);

  useEffect(() => {
    placeHeader(headerRef.current)
  }, [])

  return (
  <div className="mt-10 text-3xl mx-auto max-w-6xl">
    <div ref={headerRef}></div>
    <div>Name: react-host</div>
    <div>Framework: react</div>
    <div>Language: TypeScript</div>
    <div>CSS: Tailwind</div>
  </div>
  )
};
ReactDOM.render(<App />, document.getElementById("app"));
